### ISSUE TITLE
Error to compile the UPP4.1 program 

### ISSUE THREAD

**Issue by Ntmanh18196** [whatheway/WRFCHEM-4.3-install-script-linux-64bit#1]
Hi Will,
I got the problem when I compiled the UPP program, which is presented like that:
`/work/users/weather/user/manh/WRFCHEM-4.2.2-install-script-linux-64bit/WRFCHEM/Libs/nceplibs/lib/libg2_v3.1.0_4.a(enc_jpeg2000.o): In function `enc_jpeg2000_':
enc_jpeg2000.c:(.text+0xd6): undefined reference to `jas_stream_memopen'
enc_jpeg2000.c:(.text+0xf8): undefined reference to `jas_stream_memopen'
enc_jpeg2000.c:(.text+0x10f): undefined reference to `jpc_encode'
enc_jpeg2000.c:(.text+0x140): undefined reference to `jas_stream_close'
enc_jpeg2000.c:(.text+0x148): undefined reference to `jas_stream_close'
/work/users/weather/user/manh/WRFCHEM-4.2.2-install-script-linux-64bit/WRFCHEM/Libs/nceplibs/lib/libg2_v3.1.0_4.a(enc_png.o): In function `user_write_data':
enc_png.c:(.text+0xc): undefined reference to `png_get_io_ptr'
/work/users/weather/user/manh/WRFCHEM-4.2.2-install-script-linux-64bit/WRFCHEM/Libs/nceplibs/lib/libg2_v3.1.0_4.a(enc_png.o): In function `enc_png_':
enc_png.c:(.text+0x7c): undefined reference to `png_create_write_struct'
enc_png.c:(.text+0x91): undefined reference to `png_create_info_struct'
enc_png.c:(.text+0xb1): undefined reference to `png_set_longjmp_fn'
enc_png.c:(.text+0xe7): undefined reference to `png_set_write_fn'
enc_png.c:(.text+0x149): undefined reference to `png_set_IHDR'
enc_png.c:(.text+0x2ef): undefined reference to `png_set_rows'
enc_png.c:(.text+0x300): undefined reference to `png_write_png'
enc_png.c:(.text+0x30d): undefined reference to `png_destroy_write_struct'
enc_png.c:(.text+0x34e): undefined reference to `png_destroy_write_struct'
enc_png.c:(.text+0x377): undefined reference to `png_destroy_write_struct'
/bin/cp unipost.exe /work/users/weather/user/manh/WRFCHEM-4.2.2-install-script-linux-64bit/WRFCHEM/Downloads/UPPV4.1/exec`
Please help me to solve this issue.
Thank you very much!
Bests,
Manh,

**Comment by whatheway** [comment]
should be fixed now.
